### ISSUE TITLE
Emoji in Table

### ISSUE THREAD

**Issue by drshihan** [madskristensen/MarkdownEditor2022#119]
**Describe the bug**
In a table, Emojis are not rendered but their command text is displayed in the preview window.

**To Reproduce**
```
:x: // this works

// this doesn't work
|test|
|-|
|:x:|
```

**Expected behavior**
Render emojis within a table in the preview window.

**Comment by madskristensen** [comment]
Please report this to the Markdig parser here: https://github.com/xoofx/markdig
