### ISSUE TITLE
[Not a bug]

### ISSUE THREAD

**Issue by jeffward01** [madskristensen/MarkdownEditor2022#12]
AMAZING PLUGIN!!

Really the best one out there! you are so awesome, thank you!!

I was just wondering two things:

1. ) Is the CI Build stable?
2. ) Is the CI Build most recent (ie: If I want the latest features, I should use this one?) - Such as, does the CI Build have any features that do not exist in the market place version?

Thanks!! <3

**Comment by madskristensen** [comment]
Yes, the CI build is stable and is always the most recent. It might be the same version as what's on the Marketplace, but it will never be older. I update the Marketplace pretty frequently, but you will find newer features from time to time in the I build
