### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by kfrancis** [madskristensen/MarkdownEditor2022#13]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. I love that I can finally see the icons, that's amazing. Of course, then it would be nice to be able to know what icons I can use, if at all possible.

**Describe the solution you'd like**
As a user, I would like to be able to type `:` and then see a list of the icons I could use. Pick the icon and when selected the `:icon_name:` is closed for me so I can keep typing.

**Comment by madskristensen** [comment]
What a great idea. So, basically IntelliSense for the emoji icons once you type a colon?

**Comment by kfrancis** [comment]
(This works absolutely perfectly.)
