### ISSUE TITLE
Drag & Drop images seems to not work in folder solutions

### ISSUE THREAD

**Issue by bjornbouetsmith** [madskristensen/MarkdownEditor2022#16]
**Describe the bug**
It seems like drag and drop the the solution explorer does not work when you dont have a solution file.

i.e. if you open a folder in visual studio and open up a markdown file and want to drag an image file from the same folder where the markdown file the mouse cursor changes to the "nope" icon meaning its not possible to drop the image onto your document.

**To Reproduce**
1. Drop a markdown file in a folder
2. Place a jpg file or similar in same folder
3. Right click on folder in windows explorer and select "Open with Visual Studio"
4. Open the markdown file in the editor window
5. Try to drag the image file into the document
6. Notice the icon changes into "not possible"

**Expected behavior**
The image should be inserted as expected with proper markdown syntax where the cursor is located.

My guess is that the same problem is not present if you have your markdown files inside a project inside a .sln because then there are a lot of solution "magic" at work that this extension probably relies on to determine location of the dropped file.

**Extra info**
Strangely enough if you drag an image directly from the windows explorer into the markdown editor window, everything works as expected - it just seems like when you try to drag from the "solution" explorer for a folder solution, its disabled.

**Comment by madskristensen** [comment]
There was an issue dragging from Solution Explorer from a project or solution. However, dragging from a folder view (not .snl) is not supported by Visual Studio and is therefore not something I can implement

**Comment by bjornbouetsmith** [comment]
Shame that VS does not support this.
I have worked around thi by adding empty .sln + empty web .csproj file in same folder.
Please tell your collegues to fix this so a folder solution also have drag/drop :-)
