### ISSUE TITLE
Rendered markdown display wrong when using VS with multiple displays with different scale factors

### ISSUE THREAD

**Issue by vnbaaij** [madskristensen/MarkdownEditor2022#18]
**Describe the bug**
I'm using a SB2 with display scale set to 200%. When running VS2022 (INT Preview) on that display everything looks good: 
![image](https://user-images.githubusercontent.com/1761079/152335345-5e30a201-4c41-4014-aa36-1f7bf3d0c826.png)

I also have a 1920x1080 display attached set to 100% scale. If I move the VS instance to that screen, the rendered part of the markdown is then shown twice as big as it should be:
![image](https://user-images.githubusercontent.com/1761079/152335656-b8ee4d7d-0d01-4e1a-84db-d727d9c98007.png)

**To Reproduce**
1. Open markdown file in VS that is running on a display with a high percentage scale
2. Move the VS window to a display with a lower scale 
3. Witness the horror

**Expected behavior**
I would expect the scale/zoom to adjust to the new situation,

**Screenshots**
See description above

**Additional context**
You can make the rendered markdown look better on the 100% scale monitor by manually changing the zoom factor (CTRL+mousewheel) but the vertical scrollbar will remain very big/wide:
![image](https://user-images.githubusercontent.com/1761079/152336455-c1e30c4e-c7f9-4978-8de7-eeb68852de36.png)

P.S. This was also a problem already with the earlier version of this extension but I never reported it...

**Comment by MatthiasKargel** [comment]
Hello,

same situation here.
Environment:
- Windows 11Pro
- VS2022 64Bit (17.0.6)
- Markdown Editor v2 - 2.0.86
- Screens
  - Primary: 3440 x 2160 - Scalling 200%
  - Secondary: 3440 x 1440 - Scalling 100%

If you need someone to test or further information, im here.

BR

**Comment by madskristensen** [comment]
Ok, I know what to do and it is similar to how the old markdown editor worked.

**Comment by madskristensen** [comment]
Nope, that didn't do the trick. I think this is something I'll have to revisit when I make the switch to WebView2

**Comment by vnbaaij** [comment]
I think the problem might be in WebView2. This is what happens with the most recent PowerToys File Preview (which uses WebView2 I believe) functionality when viewing a .md file:

![image](https://user-images.githubusercontent.com/1761079/153940959-83552159-3994-4ca2-b13e-8f68eb6dfe6e.png)

Exact same issues with zoom/scrollbars way too wide
