### ISSUE TITLE
Mermaid support 

### ISSUE THREAD

**Issue by islamal5tib** [madskristensen/MarkdownEditor2022#20]
Hi there, 
any plans to support Mermaid diagrams ?

**Comment by amatlock930** [comment]
I would also like to see Mermaid support

**Comment by CFlatWouldbeMinor** [comment]
I would also like to see support for mermaid. At lease for sequence and class diagrams.

**Comment by madskristensen** [comment]
It's coming as soon as I move to WebView2 for the rendering. The latest mermaid isn't supported on the old IE 11 engine currently used

**Comment by drewnoakes** [comment]
Great news. Being able to view and edit diagrams in VS would be amazing. For now, I am copying content out to a gist, then copying back.

**Comment by ite-klass** [comment]
> It's coming as soon as I move to WebView2 for the rendering. The latest mermaid isn't supported on the old IE 11 engine currently used

How is the work coming along? Any ETA on this? Is there opportunity to support you on this?

**Comment by madskristensen** [comment]
@ite-klass a PR would be great. I just haven't had the time to look into this yet. WebView2 was added to the original Markdown editor extension, so if you look at that repo you can see how to move it into this one

**Comment by madskristensen** [comment]
Thanks to the PR by @Kissaki, we now have support for mermaid!!

![image](https://user-images.githubusercontent.com/1258877/178358893-766440f7-a6a2-40f7-a452-4ab1afe342d8.png)

Grab the latest [CI build](https://www.vsixgallery.com/extension/MarkdownEditor2022.2347dc70-1875-4775-bf48-f2b9fdfee8d4/) to try it out
