### ISSUE TITLE
IDE freezes when opening markdown files

### ISSUE THREAD

**Issue by daxpandhi** [madskristensen/MarkdownEditor2022#24]
**Describe the bug**
With the previous and current builds, I am unable to open any MD file. The IDE freezes indefinitely until the process is killed. Disabling or uninstalling the extension immediately solves the problem. I have no custom settings for the extensions, just using the defaults for the past several months.

I am happy to collect more information or share any relevant files.

**To Reproduce**
1. Install the extension.
2. Open a .md file.

**Expected behavior**
The file should open.

**Screenshots**
Not applicable.

**Additional context**
Using in Visual Studio 2022 Professional. Extension version 2.0.86.

**Comment by daxpandhi** [comment]
Sent! Here's the same file on Github as well just in case: https://github.com/QuadSpinner/Gaea-Docs/blob/master/source/Reference/04-Profile/Shaper.md

**Comment by madskristensen** [comment]
Thanks for sharing the file. It opens like any other .md file for me without any issues. It does have some unicode characters in it, so I wonder if it's because it is saved with a specific encoding that's causing the issue. What encoding is the file saved in?

**Comment by daxpandhi** [comment]
It is UTF-8. Maybe it is a conflict with something else, either on this machine or another extension perhaps. I'll try a new hive or maybe install VS in the Windows Sandbox and see if I can reproduce this. Will try it this weekend. Maybe I should build it from source and see if I can debug it that way.

**Comment by DimRochette** [comment]
Don't know if it's related but got almost all my markdown freeze/crash visual studio 17.2 preview 1. 
All of them works perfectly fine on 17.1

**Comment by ite-klass** [comment]
My VS locked up when opening an md while I had *Markdown Editor (64-bit)* and *Markdown Editor v2* installed at the same time.

After uninstalling *Markdown Editor (64-bit)* (this addons predecessor), the md file opens just fine.

@daxpandhi Do you have that installed too by any chance?

**Comment by daxpandhi** [comment]
@ite-klass - that was it! Thank you!

@madskristensen - closing the issue. This solved it.
