### ISSUE TITLE
Add 'Generate Table Of Contents' Feature 

### ISSUE THREAD

**Issue by gregpawlowski** [madskristensen/MarkdownEditor2022#25]
**Is your feature request related to a problem? Please describe.**
This is a new feature request to implement a TOC (Table of Content) markup based on headings in the Markdown document.

**Describe the solution you'd like**
A menu option that will parse the document for headings and create a clickable TOC using bullet markdown and anchor links based on the headings.

**Describe alternatives you've considered**
Currently I use VSCode to generate the TOC using Yu Zhang's markdown-all-in-one extension found here:
(Screenshot of TOC is in README)
https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

I think this feature would be a very useful addition to this extension.

**Comment by madskristensen** [comment]
So this could be a command in the context menu of the editor? Simply **right click -> Generate TOC** and boom! Is that right?

**Comment by gregpawlowski** [comment]
That would be perfect, and the TOC will generate in the space the cursor is currently resting in the document.

**Comment by madskristensen** [comment]
And if there is a selection, the generated TOC will replace what's in the selection. This is the update process as well, to keep the TOC fresh. Correct?

**Comment by gregpawlowski** [comment]
> And if there is a selection, the generated TOC will replace what's in the selection. This is the update process as well, to keep the TOC fresh. Correct?

Yes this would replace the selection and would manually need to be done to keep the TOC up to date. 

However,

An optional feature , that I forgot to mention, that would make this feature even better is that rather than manually updating TOC manually by right clicking every time, the extension can check if a TOC is present and update the TOC on Save in case any heading were changed or added.

This is also implemented in the VSCode extension above. This can be an optional setting to be changed in the extension options but it would make it easier to keep the TOS updated. Setting can be called (Update TOS On Save) and it would be a boolean set to true by default.

**Comment by madskristensen** [comment]
For the *Update on Save* feature, I love it. How would we determine that a TOC is present? If two or more headings are adjacent without any text in between?

**Comment by madskristensen** [comment]
If I got time, I'll start implementing this as part of the *Hacking Visual Studio* live stream starting in 25 minutes here: https://www.youtube.com/watch?v=p328QcgZObs

**Comment by gregpawlowski** [comment]
> For the _Update on Save_ feature, I love it. How would we determine that a TOC is present? If two or more headings are adjacent without any text in between?

An idea would be to to generate a Markdown comment when inserting TOC, then on Save simply replace the TOC between the comments.
```
<!--Start-Of-TOC-->
- [HeadingOne](#HeadingOne)
  - [SubHeading](#SubHeading)
  - [HeadingTwo](#HeadingTwo)
<!--End-Of-TOC-->
```

If a heading has no text it can be generated with not text and an anchor of #. This will help someone spot any formatting issue or misuse of heading tags.

Instead of:
```
- [HeadingOne](#HeadingOne)
```
Generate a TOC with blank heading and anchor
```
 - [](#)
```

**Comment by gregpawlowski** [comment]
> If I got time, I'll start implementing this as part of the _Hacking Visual Studio_ live stream starting in 25 minutes here: https://www.youtube.com/watch?v=p328QcgZObs

This is great! I was not aware of this live coding session, if I cannot join live due to work meetings I'll definitely watch the stream later.
