### ISSUE TITLE
hide the content menu item when the editing file is not *.md

### ISSUE THREAD

**Issue by athinboy** [madskristensen/MarkdownEditor2022#29]
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by madskristensen** [comment]
Which other files do you see the context menu items in? They don't show in C#

**Comment by cjahermanns** [comment]
Hi Mads, I noticed the items are reappearing in a *.cs file context menu after opening a *.md file (tab).
