### ISSUE TITLE
Allow styles.css override (similar to VS Code)

### ISSUE THREAD

**Issue by pdc1** [madskristensen/MarkdownEditor2022#35]
Hello, I came across your extension for Visual Studio and it looks very nice! It also appears to be even faster than Visual Studio Code 😎 

I have been working on a variety of Markdown files in VS Code, and have come to rely on the ability VS Code has to apply a custom CSS stylesheet, e.g. setting:

```json
"markdown.styles": [
  "styles.css"
]
```

This allows me to adjust markdown preview according to styles established for my project. I looked into the `Tools -> Options -> Environment -> Fonts and Colors` settings, but it does not allow me the granularity I need. For example I have a style specific to heading levels and tweaks to table layout and borders that are beyond the simple VS options. It would be great if this extension could allow the same approach or similar fine-tuning.

**Comment by madskristensen** [comment]
How should this work. Should it be per-project or global for all markdown files - or both? Can we do naming convention? For instance, the extension looks for _md-style.css_ in the same folder as the .md file or any folder above it and applies it if it exist?

**Comment by pdc1** [comment]
> How should this work. Should it be per-project or global for all markdown files - or both? Can we do naming convention? For instance, the extension looks for _md-style.css_ in the same folder as the .md file or any folder above it and applies it if it exist?

I am looking for per-project, so the folder approach implement looks good for what I need. Thanks!

**Comment by madskristensen** [comment]
@pdc1 great. Let me know how it works out for you

**Comment by pdc1** [comment]
> @pdc1 great. Let me know how it works out for you

So far so good! One thing however, my VS 2022 appears to be using Internet Explorer to preview so some of the styling is not supported/available. I do not see any options in VS to change it, is this something under the control of this extension?
