### ISSUE TITLE
Headings dropdown don't support alternative format

### ISSUE THREAD

**Issue by TishSerg** [madskristensen/MarkdownEditor2022#36]
Headings dropdown doesn't support alternative format, while preview pane does.

**To Reproduce**
See screenshots.

**Expected behavior**
Headings' names must be read while using alternative heading syntax as well as while using traditional #-based syntax.

**Screenshots**
![image](https://user-images.githubusercontent.com/11420785/164251270-d19d100a-e79a-4d21-a19d-8d7ed0ebf794.png)
![image](https://user-images.githubusercontent.com/11420785/164250275-bae04a2f-1cbb-45f9-b432-1e7fa870bf12.png)

**Comment by madskristensen** [comment]
can you paste in the markdown in a fenced code block here in a comment that reproduces the issue, please?

**Comment by TishSerg** [comment]
C'mon, man. It's so basic. See the pictures.

```
Re documentation
================

Command reference
-----------------

```

**Comment by madskristensen** [comment]
Weird. For some reason, the screenshots didn't render in my browser. Also, I don't appreciate the tone.

**Comment by TishSerg** [comment]
After you asked for an example, I was surprised and thought you were too lazy to type a few characters like it's shown on pics. I didn't know you don't see the pics. I'm sorry. I didn't want to insult you in any way.
Here's 3rd party picture hosting to see how I see [my first post](https://snipboard.io/kfWQGw.jpg): ![1st post](https://snipboard.io/kfWQGw.jpg)
