### ISSUE TITLE
No spell checking of markdown files with the extension Visual Studio Spell Checker (VS2022 and Later) installed

### ISSUE THREAD

**Issue by Molinarius** [madskristensen/MarkdownEditor2022#38]
**Describe the bug**
With the Visual Studio Spell Checker (VS2022 and Later) <https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2022andLater> extension installed, no spelling errors are shown in markdown files. They are shown however, in all other file types, and they are shown when the Markdown Editor v2 extension is disabled.

**To Reproduce**
1. Install the extensions Markdown Editor v2 and Visual Studio Spell Checker (VS2022 and Later).
2. Open a .md file.

**Expected behavior**
Spelling errors are shown in markdown files.

**Additional context**
Visual Studio 17.1.5. Of course I do not know where the root cause for this issue is and whether it is the Markdown Editor v2.

**Comment by kirsan31** [comment]
Seems it's spell checker issue, and [will be fixed](https://github.com/EWSoftware/VSSpellChecker/issues/268#issuecomment-1325452779) soon...

**Comment by kirsan31** [comment]
@Molinarius is this fixed for you? For me - [no](https://github.com/EWSoftware/VSSpellChecker/issues/268#issuecomment-1365359260) :(

**Comment by Molinarius** [comment]
> @Molinarius is this fixed for you? For me - [no](https://github.com/EWSoftware/VSSpellChecker/issues/268#issuecomment-1365359260) :(

Ooops you are right, still not working. Thanks for the hint.

**Comment by kirsan31** [comment]
@Molinarius I think that we already know that this is spell checker issue and not the md editor, we need to discuss it in appropriate [topic](https://github.com/EWSoftware/VSSpellChecker/issues/268#issuecomment-1365359260)...
