### ISSUE TITLE
Missing Quick actions and refactoring

### ISSUE THREAD

**Issue by fhtino** [madskristensen/MarkdownEditor2022#39]
MarkdownEditor "v1" had a useful option: "Quick actions and refactoring"
I think it is worth to consider to add it to "v2" too.

![image](https://user-images.githubusercontent.com/637401/165444178-1de8ae27-4cce-4ea1-b529-688be78373ae.png)

**Comment by madskristensen** [comment]
Which ones of these do you use?

**Comment by fhtino** [comment]
Sorry if I was not clear.
On VS2019 I'm using Markdown Editor 1.12.253
On VS2022 I'm using Markdown Editor V2 2.0.102
The version I'm using on VS2019 has the option "Quick actions and refactoring"

**Comment by madskristensen** [comment]
Thanks for clarifying, but I mean which one of the options in the quick actions do you use? Are they all useful, are some important ones missing? I'm trying to establish priority and scope

**Comment by fhtino** [comment]
I often use the first two, "blockquote" and "code block". Mainly because of the lack of backtick on Italian keyboard I'm using.  :)  I guess backtick is also missing on other regional keyboards.
