### ISSUE TITLE
Image Preview 

### ISSUE THREAD

**Issue by saedarm** [madskristensen/MarkdownEditor2022#44]
**Describe the bug**
Image not loading properly, even when relative reference is correct

**Screenshots**

![image](https://user-images.githubusercontent.com/42653116/170058504-dd8881fb-01d5-4f7a-8e8e-1b296f074c94.png)

![image](https://user-images.githubusercontent.com/42653116/170058559-00225231-f1c3-4e16-ae63-5bbe5bae1c62.png)

**Comment by madskristensen** [comment]
I cannot reproduce this issue. Does it still happen?

**Comment by saedarm** [comment]
Mads, seems a studio update did the trick, appreciate the response back
