### ISSUE TITLE
.md files are not editable when comparing with a version from source control

### ISSUE THREAD

**Issue by TPIvan** [madskristensen/MarkdownEditor2022#48]
**Describe the bug**
When I am comparing a code file (e.g. .vb or .cs) with its version from TFVC I can edit the current (not checked in version). When I do the same with .md file than it is not editable. 

**Expected behavior**
Current (local) version being editable when comparing with latest version from source control.
**Additional context**
I can just be a problem of Visual Studio setting.

**Comment by madskristensen** [comment]
@gundermanc how do I enable this behavior?

**Comment by TPIvan** [comment]
In `Git Changes` window, right click on a file select `Compare with Unmodified...` and when the file is .cs the `Working tree` version is editable. When the file is .md the `Working tree` version is not editable. The behavior is the same when the TFS version control is used.
I am not aware of any option for switching it on or off. 
Should I provide some images?

**Comment by gundermanc** [comment]
> @gundermanc how do I enable this behavior?

There's some sort of toggle you can set to make diffs editable, either in registry, or when creating the IVsCodeWindow (assuming that is something that you do). @quenty or @olegtk might know.

**Comment by olegtk** [comment]
Yeah, VS Diff by default only allows certain file types to be editable. We are planning to lift this restriction in 17.4. Yes, there is registry key that controls it, perhaps it can be set via pkgdef.
