### ISSUE TITLE
Math formula is not rendered in preview

### ISSUE THREAD

**Issue by DanielBuchberger** [madskristensen/MarkdownEditor2022#50]
Hi,
I was wondering if latex formula are supported? I could not get it to work properly in the preview. Markdig should support it as mentioned in [MathSpecs](https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/MathSpecs.md).

Trying to render the inline formula $a=b^2$ (Here, it works :-))
Input:
```
$a=b^2$
```
Preview Output
```
\(a=b^2\)
```

Is it supported in general? Am I missing some configuration?

It would be great, if someone could help me with this.
Except for this, the editor works absolutely great! Thanks for the great work!

**Comment by madskristensen** [comment]
Markdig transforms it to `\(a=b^2\)` but do you know if JavaScript is needed to transform it to proper math symbols?

**Comment by madskristensen** [comment]
Is it https://www.mathjax.org/ ?

**Comment by DanielBuchberger** [comment]
Mathjax should be able to interpret `\(a=b^2\)`. At least the [documentation](http://docs.mathjax.org/en/latest/basic/mathematics.html#tex-and-latex-input) states, that `\(...\)` are the default in-line delimiters. So it seems that Markdig transforms it to the format used by Mathjax.

Is it possible to include the Mathjax script somehow?
