### ISSUE TITLE
Inserting links by Quick action

### ISSUE THREAD

**Issue by SebastianVentz** [madskristensen/MarkdownEditor2022#56]
**Is your feature request related to a problem? Please describe.**
We like to use links to other md-files or even source code files for our code-near documentation. This is very time consuming as you have to:
- open target file and copy full path
- make it relative to the current md-file you want to insert the link into
- you can't look up in the solution explorerer, as links are based on file system paths
- even worse across projects

**Describe the solution you'd like**
New Quick action 'insert link', which generates a relative link to the currently selected file in solution explorer, depending on actual  md-file you executed the quick action from.
Example:
`(../../OtherProject/Interfaces/IExample.cs)`

**Comment by madskristensen** [comment]
I've added the ability to drag files from the solution explorer onto the open .md file. If it's an image it will insert an image, if not it will insert a link. In either case, the inserted URL is relative to the current file.
