### ISSUE TITLE
WebView does not scale correctly when monitors have different scaling

### ISSUE THREAD

**Issue by binginsin** [madskristensen/MarkdownEditor2022#59]
**Describe the bug**
The WebView / Browser / Viewer part of the editor does not scale correctly on one of the monitors and is zoomed in.

**To Reproduce**
1. Setup requires 2 monitors. On my setup I have one at 100% scaling and the other at 150%.
2. Open Visual Studio 2022 and open a markdown file.
3. Observe one monitor display the correct zoom level (as well as correct size for the split between editor and viewer which is 50/50 by default) on 150% scale monitor.
4. Move Visual Studio to the other monitor and observe that viewer is zoomed in and now occupies more than half of the editor screen.

**Expected behavior**
The zoom level and the split size to be the same regardless of monitor and scaling settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/17183144/179059954-908619a7-327c-4cbc-b20e-34e9a5bd2bc9.png)
![image](https://user-images.githubusercontent.com/17183144/179060004-59a354bc-53e4-4b06-932b-8d5306b12e7c.png)

**Additional context**
I realize this issue is not top priority and probably not the easiest fix in the world, since the base scaling settings are probably inside visual studio itself (which also doesn't scale some dialogs properly at times).

There are 2 properties within WebView2 that could potentially be used to fight/fix this issue
[corewebview2controller.rasterizationscale](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.rasterizationscale?view=webview2-dotnet-1.0.1264.42)
[corewebview2controller.zoomfactor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.zoomfactor?view=webview2-dotnet-1.0.1264.42#microsoft-web-webview2-core-corewebview2controller-zoomfactor)

If I have time in the near future will look at potentially fixing this myself, but if someone know exactly where the problem is and how to fix it, please do!

**Comment by madskristensen** [comment]
Is the using the latest version from the [CI build](https://www.vsixgallery.com/extension/MarkdownEditor2022.2347dc70-1875-4775-bf48-f2b9fdfee8d4)? That version now has WebView2 instead of IE and that might have solved the issue

**Comment by binginsin** [comment]
Ok so it no longer zooms in with WebView2! Awesome. 
It still changes the split screen from 50/50 to about 30/70, which would be nice to solve, however not critical.
