### ISSUE TITLE
Escaped char not rendering in preview window.

### ISSUE THREAD

**Issue by Mudoch** [madskristensen/MarkdownEditor2022#67]
**Describe the bug**
When using this line in MD file: Be careful regarding the escape char (\\) in the settings as thing will abend on load of settings.
Note I have two \\ in the above line but this editor is being stubborn too.

The preview shows: Be careful regarding the escape char () in the settings as thing will abend on load of settings.

**Expected behavior**
Should display as Be careful regarding the escape char (\) in the settings as thing will abend on load of settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/15787890/183100855-99dfefee-0f19-4cb8-ba39-7bb7a8450f9c.png)

Version is 2.0.127

**Comment by madskristensen** [comment]
Fixed with previous commit
