### ISSUE TITLE
MD preview does not show backslashes

### ISSUE THREAD

**Issue by KnieniderRobert** [madskristensen/MarkdownEditor2022#70]
**Describe the bug**
MarkdownEditor2022 preview does not show backslashes the same way Azure DevOps and Visual Studio Code do.
Tested with Visual Studio Professional 2022 (64-bit) Version 17.3.1.

**To Reproduce**
Preview attached minimal markdown file [README.md](https://github.com/madskristensen/MarkdownEditor2022/files/9392475/README.md) with [MarkdownEditor2022](https://github.com/madskristensen/MarkdownEditor2022) and Azure DevOps and and Visual Studio Code respectively.

**Expected behavior**
MarkdownEditor2022 preview shows backslashes the same way Azure DevOps and Visual Studio Code do.

**Screenshots**
- MarkdownEditor2022 (VS 17.3.1) preview
![grafik](https://user-images.githubusercontent.com/111734686/185871671-0c762c00-8cad-4644-a0dc-560a886cde12.png)

- Azur DevOps preview
![grafik](https://user-images.githubusercontent.com/111734686/185871772-c1d709cc-0953-42f0-a7fd-46f880aeb910.png)

- Visual Studio Code (1.70.1 6d9b74a) preview
![grafik](https://user-images.githubusercontent.com/111734686/185872785-651ea864-a897-4518-bb6f-bfb4f405ad56.png)

**Motivation**
Documenting Infrasctructure as Code I want to be able to read and copy Windows and UNC paths from Markdown, e.g. within PowerShell commands.

**Comment by madskristensen** [comment]
Please open this bug on the [Markdig repo](https://github.com/xoofx/markdig). This is the rendering component that the extension uses to render the HTML from the markdown source file.

**Comment by KnieniderRobert** [comment]
[xoofx](https://github.com/xoofx) essentially told me "the HTML output from Markdig looks correct to me. I don't know why MarkdownEditor2022 is displaying something different, but looks more a bug there"

**Comment by wedgberto** [comment]
Commenting out the following line fixes missing backslashes in rendered code blocks, but I assume it will break something else. https://github.com/madskristensen/MarkdownEditor2022/blob/d935432d1a2147365d12b6f567648e370c02d649/src/Margin/Browser.cs#L307

**Comment by madskristensen** [comment]
@wedgberto that might be left over from a previous implementation. It might be just fine to remove it

**Comment by KnieniderRobert** [comment]
Thank you, @wedgberto and @madskristensen!

I confirm that the bugfix works as expected.

MarkdownEditor2022 (2.0.130 in VisualStudio 17.3.1) preview shows backslashes the same way Azure DevOps and Visual Studio Code do:
![grafik](https://user-images.githubusercontent.com/111734686/187151195-cc604cf6-c642-4aff-b754-2b3c96358011.png)
