### ISSUE TITLE
Re-add math syntax (LaTex) support

### ISSUE THREAD

**Issue by jp-diegidio** [madskristensen/MarkdownEditor2022#74]
Hi there,

LaTex support (with mathjax) was added on 13 Jul with commit https://github.com/madskristensen/MarkdownEditor2022/commit/b9d62c4e5c9b9f9b3f1c529c01046accd676b3cd

but was then removed (commented out) on 2 Aug with commit https://github.com/madskristensen/MarkdownEditor2022/commit/d935432d1a2147365d12b6f567648e370c02d649

(Was there any specific reason to comment mathjax out?  I just cannot guess any issue with having the script in.  I'd be glad to help if needed.)

Can we have this very important feature back/fixed, please?

**Comment by madskristensen** [comment]
I couldn't get it working after moving to WebView2

**Comment by jp-diegidio** [comment]
Hi again,

The good news is I have got it working with very little modification: in Browser.cs, how the mathjax script is loaded and later refreshed, plus it is not sufficient to have only the mathjax script locally, depending on configuration additional components are needed.

Now, I am assuming a fine-tuning of the mathjax configuration you could do yourself later and at any time, still I'd need to ask you a couple of things before I can close:

- What input and output components should we load?  All of them?  Or, vice versa, maybe the tex-chtml only?
- Related to the previous one, since it allows access to additional functionality: would you like the rendered formula context menu to stay enabled?
- Anything else you'd like me to put it/configure in a specific way?

(As for the first question, I'd simply put the whole mathjax distribution in, so anything can be done and you'd have full control in configuration, as well as then the user via the context menu...  Unless you prefer a more controlled and restricted access to the math functionality.)

Looking forward to your feedback.

**Comment by jp-diegidio** [comment]
I have meanwhile forked and branched, and you can see the (initial) fixes here: https://github.com/jp-diegidio/MarkdownEditor2022/commit/07a01352acee680bc9b9acfd1692be02f90fefb5

To recap, there are at least two things missing:
- Fix/finalize mathjax configuration;  [important]
- Have the mathjax package locally instead of from a CDN.  [trivial but depends on the previous one]

Le me know your thoughts, how you'd like to proceed...

**Comment by LexaGV** [comment]
Not sure why MD should support Math. MD is "HTML for imbeciles" - very simplified version of "formatting language". So simplified that you cannot even specify color for text! :facepalm: In this light why you would need to use so rare thing like MathML/LaTeX?

**Comment by jp-diegidio** [comment]
(@LexaGV : For one who is not even sure, you write nonsense pretty confidently.)

FYI, I am out of this project: this tool is so badly conceived that it regenerates all output at every single keystroke, but the author apparently is committed to not let anything happen but his bumping of versions up.

**Comment by jp-diegidio** [comment]
(@LexaGV : For one who is not even sure, you write nonsense pretty confidently.)

FYI, I am out of this project: this tool is so badly conceived that it regenerates all output at every single keystroke, but the author apparently is committed to not let anything happen but his bumping of versions up.
