### ISSUE TITLE
Images not shown in preview

### ISSUE THREAD

**Issue by MV10** [madskristensen/MarkdownEditor2022#83]
The preview window shows the "broken image" placeholder.

As you can see from the screenshots, I'm using relative paths, but I tried a full path, too (which was just to replace the `../` prefix with `/foldername/` ... not completely sure if that's right, never had to do it that way before). The Edge dev tools network tab shows an odd-looking request URL. Over the past several years, I've written many articles using your editor, so I've used this relative path syntax a lot, this is the first time I've seen this.

MD Editor v2.0.130
VS2022 Community v17.4.3
MS Edge 108.0.1462.54

Preview window:
![image](https://user-images.githubusercontent.com/794270/209568890-212482d3-0e87-443e-8738-39f902fca602.png)

MD reference and path:
![image](https://user-images.githubusercontent.com/794270/209568918-968370da-2781-46c5-a5a6-40ffd4fae090.png)

F12 network tab:
![image](https://user-images.githubusercontent.com/794270/209568983-022b599f-09de-4b32-a01f-0e148c445700.png)

**Comment by sean-bloch** [comment]
@MV10 I found your post after I had some issues with images. 

As a workaround, when I save the .html to disk, I see in the HTML markup (e.g., "view source") for example 

`<img src="http://browsing-file-host/img/myimage.png"/>`
(if i saved to an /img/ folder in the path of the .md file...)

I do find/replace to replace `http://browsing-file-host` with `.`. The markup becomes for example:

`<img src="./img/myimage.png"/>`

and the images load when I open in a browser.

**Comment by UweKeim** [comment]
I'm having the same issue. Relative URLs to links and images that sit in parent folders are not resolved.

This bug even exists in the built-in Markdown editor of VS 2022 Preview.

[I've reported it here](https://developercommunity.visualstudio.com/t/10337706), hope they'll fix it.

**Comment by MV10** [comment]
The issue persists in v2.0.132 released in April 2023.

**Comment by MV10** [comment]
No change in v2.0.143 released in August 2023.

**Comment by MV10** [comment]
Still happening in November 2023's v2.0.149 ... pretty annoying.
